data_path: 'data/synth'
error_out_name: '%sprediction_errors_%dstep.npy'
gpu: false
num_dims: 2
input_size: 4
input_time_steps: 50
load_best_model: true
num_vars: 3
pos_representation: 'polar'
prior_variance: 5.0e-05
report_error_norm: true
test_burn_in_steps: 25
vel_norm_norm: true
same_data_norm: false
symmetric_data_norm: false
no_data_norm: false
working_dir: 'results/synth/locs_demo/seed_1'
model_type: 'standalone_fc_locs'
graph_type: 'dynamic'
network_type: 'markov'
decoder_dropout: 0.0
decoder_hidden: 256
seed: 1
batch_size: 16
lr: 5.0e-04
use_adam: true
num_epochs: 400
lr_decay_factor: 0.5
lr_decay_steps: 400
normalize_nll: true
tune_on_nll: true
val_teacher_forcing: true
teacher_forcing_steps: -1
